# Generated by Django 5.2.3 on 2025-06-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duxbed_innovation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_your_cart',
            name='image',
            field=models.ImageField(upload_to='fill_your_cart'),
        ),
    ]
