# Generated by Django 5.2.3 on 2025-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duxbed_innovation_app', '0002_alter_fill_your_cart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bed_cot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='bed_cot')),
            ],
        ),
    ]
