# Generated by Django 5.2.3 on 2025-06-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duxbed_innovation_app', '0004_sofa_come_bed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bed_cot',
        ),
        migrations.DeleteModel(
            name='fill_your_cart',
        ),
        migrations.DeleteModel(
            name='sofa_come_bed',
        ),
    ]
