# Generated by Django 5.2.3 on 2025-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duxbed_innovation_app', '0007_remove_product_details_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fill_your_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='fill_your_cart')),
            ],
        ),
    ]
