# Generated by Django 5.2.3 on 2025-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duxbed_innovation_app', '0008_fill_your_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
