# Generated by Django 5.2.3 on 2025-06-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duxbed_innovation_app', '0009_product_details_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
